name: ExcellentVARO
author: Kreavita
version: 1.0
description: Excellent VARO Plugin for Excellent Students
main: net.kreaverse.ExcellentVARO
api-version: 1.18
commands:
 start:
  description: start the game. You can change the countdown, the default countdown is 0.
  usage: /start [<Countdown>]
 reset:
  description: reset the game
  usage: /reset
 varokill:
  description: remove a player from the game
  usage: /varokill <player>
 varorevive:
  description: remove a player from the game
  usage: /varorevive <player>
 stats:
  description: show the statistics of a player
  usage: /stats <player>
 team:
  description: send a team request to a player or accepts it
  usage: /team <player>
 unteam:
  description: disbands your current team
  usage: /unteam
 pause:
  description: pause the game, 2 minutes by default
  usage: /pause [<minutes>]
 unpause:
  description: unpause the game, with a delay of 5 seconds
  usage: /unpause